// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package database

import (
	"context"
	"database/sql"
)

const addCategoryUploader = `-- name: AddCategoryUploader :exec
INSERT INTO category_uploaders (category_id, user_id) VALUES (?, ?)
`

type AddCategoryUploaderParams struct {
	CategoryID string
	UserID     string
}

func (q *Queries) AddCategoryUploader(ctx context.Context, arg AddCategoryUploaderParams) error {
	_, err := q.db.ExecContext(ctx, addCategoryUploader, arg.CategoryID, arg.UserID)
	return err
}

const clearCategoryUploaders = `-- name: ClearCategoryUploaders :exec
DELETE FROM category_uploaders WHERE category_id = ?
`

func (q *Queries) ClearCategoryUploaders(ctx context.Context, categoryID string) error {
	_, err := q.db.ExecContext(ctx, clearCategoryUploaders, categoryID)
	return err
}

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesByUploader = `-- name: CountCategoriesByUploader :one
SELECT COUNT(*) FROM categories c JOIN category_uploaders cu ON cu.category_id = c.id WHERE cu.user_id = ?
`

func (q *Queries) CountCategoriesByUploader(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesByUploader, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (id, name, description, created_by) VALUES (?, ?, ?, ?)
`

type CreateCategoryParams struct {
	ID          string
	Name        string
	Description string
	CreatedBy   string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, description, created_by, created_at FROM categories WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryUploaders = `-- name: GetCategoryUploaders :many
SELECT user_id FROM category_uploaders WHERE category_id = ?
`

func (q *Queries) GetCategoryUploaders(ctx context.Context, categoryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryUploaders, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryVideoCount = `-- name: GetCategoryVideoCount :one
SELECT COUNT(*) FROM resources WHERE category_id = ?
`

func (q *Queries) GetCategoryVideoCount(ctx context.Context, categoryID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCategoryVideoCount, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isUploaderAuthorized = `-- name: IsUploaderAuthorized :one
SELECT COUNT(*) FROM category_uploaders WHERE category_id = ? AND user_id = ?
`

type IsUploaderAuthorizedParams struct {
	CategoryID string
	UserID     string
}

func (q *Queries) IsUploaderAuthorized(ctx context.Context, arg IsUploaderAuthorizedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isUploaderAuthorized, arg.CategoryID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description, created_by, created_at FROM categories ORDER BY created_at DESC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByUploader = `-- name: ListCategoriesByUploader :many
SELECT c.id, c.name, c.description, c.created_by, c.created_at FROM categories c JOIN category_uploaders cu ON cu.category_id = c.id WHERE cu.user_id = ? ORDER BY c.created_at DESC
`

func (q *Queries) ListCategoriesByUploader(ctx context.Context, userID string) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByUploader, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByUploaderPaginated = `-- name: ListCategoriesByUploaderPaginated :many
SELECT c.id, c.name, c.description, c.created_by, c.created_at FROM categories c JOIN category_uploaders cu ON cu.category_id = c.id WHERE cu.user_id = ? ORDER BY c.created_at DESC LIMIT ? OFFSET ?
`

type ListCategoriesByUploaderPaginatedParams struct {
	UserID string
	Limit  int64
	Offset int64
}

func (q *Queries) ListCategoriesByUploaderPaginated(ctx context.Context, arg ListCategoriesByUploaderPaginatedParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByUploaderPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesPaginated = `-- name: ListCategoriesPaginated :many
SELECT id, name, description, created_by, created_at FROM categories ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListCategoriesPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListCategoriesPaginated(ctx context.Context, arg ListCategoriesPaginatedParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
