// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package database

import (
	"context"
	"database/sql"
)

const addUploader = `-- name: AddUploader :exec
INSERT INTO category_users (category_name, name, can_upload) VALUES (?, ?, ?)
`

type AddUploaderParams struct {
	CategoryName string
	Name         string
	CanUpload    int64
}

func (q *Queries) AddUploader(ctx context.Context, arg AddUploaderParams) error {
	_, err := q.db.ExecContext(ctx, addUploader, arg.CategoryName, arg.Name, arg.CanUpload)
	return err
}

const canUpload = `-- name: CanUpload :one
SELECT COUNT(*) FROM category_users WHERE category_name = ? AND name = ? AND can_upload = 1
`

type CanUploadParams struct {
	CategoryName string
	Name         string
}

func (q *Queries) CanUpload(ctx context.Context, arg CanUploadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, canUpload, arg.CategoryName, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clearCategoryUploaders = `-- name: ClearCategoryUploaders :exec
DELETE FROM category_users WHERE category_name = ?
`

func (q *Queries) ClearCategoryUploaders(ctx context.Context, categoryName string) error {
	_, err := q.db.ExecContext(ctx, clearCategoryUploaders, categoryName)
	return err
}

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesByUploader = `-- name: CountCategoriesByUploader :one
SELECT COUNT(*) FROM categories c JOIN category_users cu ON cu.category_name = c.name WHERE cu.name = ? AND cu.can_upload = 1
`

func (q *Queries) CountCategoriesByUploader(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesByUploader, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (name, display_name, description, created_by) VALUES (?, ?, ?, ?)
`

type CreateCategoryParams struct {
	Name        string
	DisplayName string
	Description string
	CreatedBy   string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.CreatedBy,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE name = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, name)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT name, display_name, description, created_by, created_at FROM categories WHERE name = ?
`

func (q *Queries) GetCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, name)
	var i Category
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryVideoCount = `-- name: GetCategoryVideoCount :one
SELECT COUNT(*) FROM resources WHERE category_name = ?
`

func (q *Queries) GetCategoryVideoCount(ctx context.Context, categoryName sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCategoryVideoCount, categoryName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isAssigned = `-- name: IsAssigned :one
SELECT COUNT(*) FROM category_users WHERE category_name = ? AND name = ?
`

type IsAssignedParams struct {
	CategoryName string
	Name         string
}

func (q *Queries) IsAssigned(ctx context.Context, arg IsAssignedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isAssigned, arg.CategoryName, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCategories = `-- name: ListCategories :many
SELECT name, display_name, description, created_by, created_at FROM categories ORDER BY created_at DESC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByUploader = `-- name: ListCategoriesByUploader :many
SELECT c.name, c.display_name, c.description, c.created_by, c.created_at FROM categories c JOIN category_users cu ON cu.category_name = c.name WHERE cu.name = ? AND cu.can_upload = 1 ORDER BY c.created_at DESC
`

func (q *Queries) ListCategoriesByUploader(ctx context.Context, name string) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByUploader, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByUploaderPaginated = `-- name: ListCategoriesByUploaderPaginated :many
SELECT c.name, c.display_name, c.description, c.created_by, c.created_at FROM categories c JOIN category_users cu ON cu.category_name = c.name WHERE cu.name = ? AND cu.can_upload = 1 ORDER BY c.created_at DESC LIMIT ? OFFSET ?
`

type ListCategoriesByUploaderPaginatedParams struct {
	Name   string
	Limit  int64
	Offset int64
}

func (q *Queries) ListCategoriesByUploaderPaginated(ctx context.Context, arg ListCategoriesByUploaderPaginatedParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByUploaderPaginated, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesPaginated = `-- name: ListCategoriesPaginated :many
SELECT name, display_name, description, created_by, created_at FROM categories ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListCategoriesPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListCategoriesPaginated(ctx context.Context, arg ListCategoriesPaginatedParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploaders = `-- name: ListUploaders :many
SELECT name, can_upload FROM category_users WHERE category_name = ?
`

type ListUploadersRow struct {
	Name      string
	CanUpload int64
}

func (q *Queries) ListUploaders(ctx context.Context, categoryName string) ([]ListUploadersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUploaders, categoryName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUploadersRow{}
	for rows.Next() {
		var i ListUploadersRow
		if err := rows.Scan(&i.Name, &i.CanUpload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUploader = `-- name: RemoveUploader :exec
DELETE FROM category_users WHERE category_name = ? AND name = ?
`

type RemoveUploaderParams struct {
	CategoryName string
	Name         string
}

func (q *Queries) RemoveUploader(ctx context.Context, arg RemoveUploaderParams) error {
	_, err := q.db.ExecContext(ctx, removeUploader, arg.CategoryName, arg.Name)
	return err
}
