// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	Token     string
	UserID    string
	UserRole  string
	Username  string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Category struct {
	Name        string
	DisplayName string
	Description string
	CreatedBy   string
	CreatedAt   time.Time
}

type CategoryUser struct {
	CategoryName string
	UserID       string
}

type Playlist struct {
	ID           string
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

type PlaylistVideo struct {
	PlaylistID string
	ResourceID string
	SortOrder  int64
}

type Resource struct {
	ID              string
	Title           string
	Filename        string
	FileSize        int64
	ContentType     string
	ResourceType    string
	Views           int64
	UploadedBy      sql.NullString
	CategoryName    sql.NullString
	TranscodeStatus string
	Banned          int64
	NoTranscode     int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type ShareLink struct {
	ID         string
	ResourceID string
	Password   string
	ExpiresAt  sql.NullTime
	CreatedBy  sql.NullString
	CreatedAt  time.Time
}

type User struct {
	ID          string
	Username    string
	TotpSecret  string
	DisplayName string
	Role        string
	CreatedAt   time.Time
}
