// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          string
	Name        string
	Description string
	CreatedBy   string
	CreatedAt   time.Time
}

type CategoryUploader struct {
	CategoryID string
	UserID     string
}

type Playlist struct {
	ID          string
	CategoryID  string
	Name        string
	Description string
	CreatedBy   string
	SortOrder   int64
	CreatedAt   time.Time
}

type PlaylistVideo struct {
	PlaylistID string
	ResourceID string
	SortOrder  int64
}

type Resource struct {
	ID              string
	Title           string
	PasswordHash    string
	Filename        string
	FileSize        int64
	ContentType     string
	Views           int64
	UploadedBy      sql.NullString
	CategoryID      sql.NullString
	TranscodeStatus string
	Banned          int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type User struct {
	ID         string
	Username   string
	TotpSecret string
	Role       string
	CreatedAt  time.Time
}
