// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	Token     string
	Username  string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Category struct {
	Name        string
	DisplayName string
	Description string
	CreatedBy   string
	CreatedAt   time.Time
}

type CategoryUser struct {
	CategoryName string
	Name         string
	CanUpload    int64
}

type Playlist struct {
	Name         string
	CategoryName string
	PlaylistType string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

type PlaylistVideo struct {
	PlaylistCategoryName string
	PlaylistName         string
	ResourceID           string
	SortOrder            int64
}

type Resource struct {
	ID              string
	Title           string
	Filename        string
	FileSize        int64
	ContentType     string
	ResourceType    string
	Views           int64
	UploadedBy      string
	TranscodeStatus string
	Banned          int64
	NoTranscode     int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ResourceCategory struct {
	ResourceID   string
	CategoryName string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type ShareLink struct {
	ID         string
	Password   string
	TargetType string
	TargetID   string
	ExpiresAt  sql.NullTime
	CreatedBy  string
	CreatedAt  time.Time
}

type ShareResource struct {
	ResourceID string
	Password   string
	ExpiresAt  sql.NullTime
	CreatedBy  string
	CreatedAt  time.Time
}

type User struct {
	Name        string
	TotpSecret  string
	DisplayName string
	IsAdmin     int64
	CreatedAt   time.Time
}
