// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist.sql

package database

import (
	"context"
	"time"
)

const addVideoToPlaylist = `-- name: AddVideoToPlaylist :exec
INSERT INTO playlist_videos (playlist_category_name, playlist_name, resource_id, sort_order) VALUES (?, ?, ?, ?) ON CONFLICT(playlist_category_name, playlist_name, resource_id) DO UPDATE SET sort_order = EXCLUDED.sort_order
`

type AddVideoToPlaylistParams struct {
	PlaylistCategoryName string
	PlaylistName         string
	ResourceID           string
	SortOrder            int64
}

func (q *Queries) AddVideoToPlaylist(ctx context.Context, arg AddVideoToPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, addVideoToPlaylist,
		arg.PlaylistCategoryName,
		arg.PlaylistName,
		arg.ResourceID,
		arg.SortOrder,
	)
	return err
}

const countPlaylists = `-- name: CountPlaylists :one
SELECT COUNT(*) FROM playlists
`

func (q *Queries) CountPlaylists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlaylistsByCategory = `-- name: CountPlaylistsByCategory :one
SELECT COUNT(*) FROM playlists WHERE category_name = ?
`

func (q *Queries) CountPlaylistsByCategory(ctx context.Context, categoryName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistsByCategory, categoryName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlaylistsByCategoryAndType = `-- name: CountPlaylistsByCategoryAndType :one
SELECT COUNT(*) FROM playlists WHERE category_name = ? AND playlist_type = ?
`

type CountPlaylistsByCategoryAndTypeParams struct {
	CategoryName string
	PlaylistType string
}

func (q *Queries) CountPlaylistsByCategoryAndType(ctx context.Context, arg CountPlaylistsByCategoryAndTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistsByCategoryAndType, arg.CategoryName, arg.PlaylistType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlaylistsByType = `-- name: CountPlaylistsByType :one
SELECT COUNT(*) FROM playlists WHERE playlist_type = ?
`

func (q *Queries) CountPlaylistsByType(ctx context.Context, playlistType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistsByType, playlistType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :exec
INSERT INTO playlists (category_name, playlist_type, name, display_name, description, created_by, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePlaylistParams struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, createPlaylist,
		arg.CategoryName,
		arg.PlaylistType,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.CreatedBy,
		arg.SortOrder,
	)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE category_name = ? AND name = ?
`

type DeletePlaylistParams struct {
	CategoryName string
	Name         string
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, arg.CategoryName, arg.Name)
	return err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE category_name = ? AND name = ?
`

type GetPlaylistParams struct {
	CategoryName string
	Name         string
}

type GetPlaylistRow struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

func (q *Queries) GetPlaylist(ctx context.Context, arg GetPlaylistParams) (GetPlaylistRow, error) {
	row := q.db.QueryRowContext(ctx, getPlaylist, arg.CategoryName, arg.Name)
	var i GetPlaylistRow
	err := row.Scan(
		&i.CategoryName,
		&i.PlaylistType,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedBy,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaylistsForResource = `-- name: GetPlaylistsForResource :many
SELECT playlist_category_name, playlist_name FROM playlist_videos WHERE resource_id = ?
`

type GetPlaylistsForResourceRow struct {
	PlaylistCategoryName string
	PlaylistName         string
}

func (q *Queries) GetPlaylistsForResource(ctx context.Context, resourceID string) ([]GetPlaylistsForResourceRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistsForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlaylistsForResourceRow{}
	for rows.Next() {
		var i GetPlaylistsForResourceRow
		if err := rows.Scan(&i.PlaylistCategoryName, &i.PlaylistName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlaylists = `-- name: ListAllPlaylists :many
SELECT category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists ORDER BY sort_order ASC, created_at ASC
`

type ListAllPlaylistsRow struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

func (q *Queries) ListAllPlaylists(ctx context.Context) ([]ListAllPlaylistsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlaylistsRow{}
	for rows.Next() {
		var i ListAllPlaylistsRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistVideos = `-- name: ListPlaylistVideos :many
SELECT resource_id FROM playlist_videos WHERE playlist_category_name = ? AND playlist_name = ? ORDER BY sort_order ASC
`

type ListPlaylistVideosParams struct {
	PlaylistCategoryName string
	PlaylistName         string
}

func (q *Queries) ListPlaylistVideos(ctx context.Context, arg ListPlaylistVideosParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistVideos, arg.PlaylistCategoryName, arg.PlaylistName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var resource_id string
		if err := rows.Scan(&resource_id); err != nil {
			return nil, err
		}
		items = append(items, resource_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByCategory = `-- name: ListPlaylistsByCategory :many
SELECT category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE category_name = ? ORDER BY sort_order ASC, created_at ASC
`

type ListPlaylistsByCategoryRow struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

func (q *Queries) ListPlaylistsByCategory(ctx context.Context, categoryName string) ([]ListPlaylistsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByCategory, categoryName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistsByCategoryRow{}
	for rows.Next() {
		var i ListPlaylistsByCategoryRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByCategoryAndType = `-- name: ListPlaylistsByCategoryAndType :many
SELECT category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE category_name = ? AND playlist_type = ? ORDER BY sort_order ASC, created_at ASC
`

type ListPlaylistsByCategoryAndTypeParams struct {
	CategoryName string
	PlaylistType string
}

type ListPlaylistsByCategoryAndTypeRow struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

func (q *Queries) ListPlaylistsByCategoryAndType(ctx context.Context, arg ListPlaylistsByCategoryAndTypeParams) ([]ListPlaylistsByCategoryAndTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByCategoryAndType, arg.CategoryName, arg.PlaylistType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistsByCategoryAndTypeRow{}
	for rows.Next() {
		var i ListPlaylistsByCategoryAndTypeRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByCategoryAndTypePaginated = `-- name: ListPlaylistsByCategoryAndTypePaginated :many
SELECT category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE category_name = ? AND playlist_type = ? ORDER BY sort_order ASC, created_at ASC LIMIT ? OFFSET ?
`

type ListPlaylistsByCategoryAndTypePaginatedParams struct {
	CategoryName string
	PlaylistType string
	Limit        int64
	Offset       int64
}

type ListPlaylistsByCategoryAndTypePaginatedRow struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

func (q *Queries) ListPlaylistsByCategoryAndTypePaginated(ctx context.Context, arg ListPlaylistsByCategoryAndTypePaginatedParams) ([]ListPlaylistsByCategoryAndTypePaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByCategoryAndTypePaginated,
		arg.CategoryName,
		arg.PlaylistType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistsByCategoryAndTypePaginatedRow{}
	for rows.Next() {
		var i ListPlaylistsByCategoryAndTypePaginatedRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByCategoryPaginated = `-- name: ListPlaylistsByCategoryPaginated :many
SELECT category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE category_name = ? ORDER BY sort_order ASC, created_at ASC LIMIT ? OFFSET ?
`

type ListPlaylistsByCategoryPaginatedParams struct {
	CategoryName string
	Limit        int64
	Offset       int64
}

type ListPlaylistsByCategoryPaginatedRow struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

func (q *Queries) ListPlaylistsByCategoryPaginated(ctx context.Context, arg ListPlaylistsByCategoryPaginatedParams) ([]ListPlaylistsByCategoryPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByCategoryPaginated, arg.CategoryName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistsByCategoryPaginatedRow{}
	for rows.Next() {
		var i ListPlaylistsByCategoryPaginatedRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByType = `-- name: ListPlaylistsByType :many
SELECT category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE playlist_type = ? ORDER BY sort_order ASC, created_at ASC
`

type ListPlaylistsByTypeRow struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

func (q *Queries) ListPlaylistsByType(ctx context.Context, playlistType string) ([]ListPlaylistsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByType, playlistType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistsByTypeRow{}
	for rows.Next() {
		var i ListPlaylistsByTypeRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByTypePaginated = `-- name: ListPlaylistsByTypePaginated :many
SELECT category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE playlist_type = ? ORDER BY sort_order ASC, created_at ASC LIMIT ? OFFSET ?
`

type ListPlaylistsByTypePaginatedParams struct {
	PlaylistType string
	Limit        int64
	Offset       int64
}

type ListPlaylistsByTypePaginatedRow struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

func (q *Queries) ListPlaylistsByTypePaginated(ctx context.Context, arg ListPlaylistsByTypePaginatedParams) ([]ListPlaylistsByTypePaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByTypePaginated, arg.PlaylistType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistsByTypePaginatedRow{}
	for rows.Next() {
		var i ListPlaylistsByTypePaginatedRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsPaginated = `-- name: ListPlaylistsPaginated :many
SELECT category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists ORDER BY sort_order ASC, created_at ASC LIMIT ? OFFSET ?
`

type ListPlaylistsPaginatedParams struct {
	Limit  int64
	Offset int64
}

type ListPlaylistsPaginatedRow struct {
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
	CreatedAt    time.Time
}

func (q *Queries) ListPlaylistsPaginated(ctx context.Context, arg ListPlaylistsPaginatedParams) ([]ListPlaylistsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistsPaginatedRow{}
	for rows.Next() {
		var i ListPlaylistsPaginatedRow
		if err := rows.Scan(
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeVideoFromPlaylist = `-- name: RemoveVideoFromPlaylist :exec
DELETE FROM playlist_videos WHERE playlist_category_name = ? AND playlist_name = ? AND resource_id = ?
`

type RemoveVideoFromPlaylistParams struct {
	PlaylistCategoryName string
	PlaylistName         string
	ResourceID           string
}

func (q *Queries) RemoveVideoFromPlaylist(ctx context.Context, arg RemoveVideoFromPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, removeVideoFromPlaylist, arg.PlaylistCategoryName, arg.PlaylistName, arg.ResourceID)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :exec
UPDATE playlists SET display_name = ?, description = ?, sort_order = ? WHERE category_name = ? AND name = ?
`

type UpdatePlaylistParams struct {
	DisplayName  string
	Description  string
	SortOrder    int64
	CategoryName string
	Name         string
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylist,
		arg.DisplayName,
		arg.Description,
		arg.SortOrder,
		arg.CategoryName,
		arg.Name,
	)
	return err
}
