// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist.sql

package database

import (
	"context"
)

const addVideoToPlaylist = `-- name: AddVideoToPlaylist :exec
INSERT INTO playlist_videos (playlist_id, resource_id, sort_order) VALUES (?, ?, ?) ON CONFLICT(playlist_id, resource_id) DO UPDATE SET sort_order = EXCLUDED.sort_order
`

type AddVideoToPlaylistParams struct {
	PlaylistID string
	ResourceID string
	SortOrder  int64
}

func (q *Queries) AddVideoToPlaylist(ctx context.Context, arg AddVideoToPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, addVideoToPlaylist, arg.PlaylistID, arg.ResourceID, arg.SortOrder)
	return err
}

const countPlaylists = `-- name: CountPlaylists :one
SELECT COUNT(*) FROM playlists
`

func (q *Queries) CountPlaylists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlaylistsByType = `-- name: CountPlaylistsByType :one
SELECT COUNT(*) FROM playlists WHERE playlist_type = ?
`

func (q *Queries) CountPlaylistsByType(ctx context.Context, playlistType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistsByType, playlistType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :exec
INSERT INTO playlists (id, category_name, playlist_type, name, display_name, description, created_by, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePlaylistParams struct {
	ID           string
	CategoryName string
	PlaylistType string
	Name         string
	DisplayName  string
	Description  string
	CreatedBy    string
	SortOrder    int64
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, createPlaylist,
		arg.ID,
		arg.CategoryName,
		arg.PlaylistType,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.CreatedBy,
		arg.SortOrder,
	)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = ?
`

func (q *Queries) DeletePlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, id)
	return err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE id = ?
`

func (q *Queries) GetPlaylist(ctx context.Context, id string) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylist, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.PlaylistType,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CreatedBy,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaylistsForResource = `-- name: GetPlaylistsForResource :many
SELECT playlist_id FROM playlist_videos WHERE resource_id = ?
`

func (q *Queries) GetPlaylistsForResource(ctx context.Context, resourceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistsForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var playlist_id string
		if err := rows.Scan(&playlist_id); err != nil {
			return nil, err
		}
		items = append(items, playlist_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlaylists = `-- name: ListAllPlaylists :many
SELECT id, category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListAllPlaylists(ctx context.Context) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistVideos = `-- name: ListPlaylistVideos :many
SELECT resource_id FROM playlist_videos WHERE playlist_id = ? ORDER BY sort_order ASC
`

func (q *Queries) ListPlaylistVideos(ctx context.Context, playlistID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistVideos, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var resource_id string
		if err := rows.Scan(&resource_id); err != nil {
			return nil, err
		}
		items = append(items, resource_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByCategory = `-- name: ListPlaylistsByCategory :many
SELECT id, category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE category_name = ? ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListPlaylistsByCategory(ctx context.Context, categoryName string) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByCategory, categoryName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByCategoryAndType = `-- name: ListPlaylistsByCategoryAndType :many
SELECT id, category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE category_name = ? AND playlist_type = ? ORDER BY sort_order ASC, created_at ASC
`

type ListPlaylistsByCategoryAndTypeParams struct {
	CategoryName string
	PlaylistType string
}

func (q *Queries) ListPlaylistsByCategoryAndType(ctx context.Context, arg ListPlaylistsByCategoryAndTypeParams) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByCategoryAndType, arg.CategoryName, arg.PlaylistType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByType = `-- name: ListPlaylistsByType :many
SELECT id, category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE playlist_type = ? ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListPlaylistsByType(ctx context.Context, playlistType string) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByType, playlistType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByTypePaginated = `-- name: ListPlaylistsByTypePaginated :many
SELECT id, category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists WHERE playlist_type = ? ORDER BY sort_order ASC, created_at ASC LIMIT ? OFFSET ?
`

type ListPlaylistsByTypePaginatedParams struct {
	PlaylistType string
	Limit        int64
	Offset       int64
}

func (q *Queries) ListPlaylistsByTypePaginated(ctx context.Context, arg ListPlaylistsByTypePaginatedParams) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByTypePaginated, arg.PlaylistType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsPaginated = `-- name: ListPlaylistsPaginated :many
SELECT id, category_name, playlist_type, name, display_name, description, created_by, sort_order, created_at FROM playlists ORDER BY sort_order ASC, created_at ASC LIMIT ? OFFSET ?
`

type ListPlaylistsPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPlaylistsPaginated(ctx context.Context, arg ListPlaylistsPaginatedParams) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.PlaylistType,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeVideoFromPlaylist = `-- name: RemoveVideoFromPlaylist :exec
DELETE FROM playlist_videos WHERE playlist_id = ? AND resource_id = ?
`

type RemoveVideoFromPlaylistParams struct {
	PlaylistID string
	ResourceID string
}

func (q *Queries) RemoveVideoFromPlaylist(ctx context.Context, arg RemoveVideoFromPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, removeVideoFromPlaylist, arg.PlaylistID, arg.ResourceID)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :exec
UPDATE playlists SET name = ?, display_name = ?, description = ?, sort_order = ? WHERE id = ?
`

type UpdatePlaylistParams struct {
	Name        string
	DisplayName string
	Description string
	SortOrder   int64
	ID          string
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylist,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
