// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package database

import (
	"context"
	"database/sql"
)

const countResources = `-- name: CountResources :one
SELECT COUNT(*) FROM resources
`

func (q *Queries) CountResources(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourcesByUploader = `-- name: CountResourcesByUploader :one
SELECT COUNT(*) FROM resources WHERE uploaded_by = ?
`

func (q *Queries) CountResourcesByUploader(ctx context.Context, uploadedBy sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResourcesByUploader, uploadedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :exec
INSERT INTO resources (id, title, password_hash, filename, file_size, content_type, uploaded_by, category_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateResourceParams struct {
	ID           string
	Title        string
	PasswordHash string
	Filename     string
	FileSize     int64
	ContentType  string
	UploadedBy   sql.NullString
	CategoryID   sql.NullString
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) error {
	_, err := q.db.ExecContext(ctx, createResource,
		arg.ID,
		arg.Title,
		arg.PasswordHash,
		arg.Filename,
		arg.FileSize,
		arg.ContentType,
		arg.UploadedBy,
		arg.CategoryID,
	)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, title, password_hash, filename, file_size, content_type, views, uploaded_by, category_id, transcode_status, created_at, updated_at FROM resources WHERE id = ?
`

func (q *Queries) GetResource(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PasswordHash,
		&i.Filename,
		&i.FileSize,
		&i.ContentType,
		&i.Views,
		&i.UploadedBy,
		&i.CategoryID,
		&i.TranscodeStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementResourceViews = `-- name: IncrementResourceViews :exec
UPDATE resources SET views = views + 1 WHERE id = ?
`

func (q *Queries) IncrementResourceViews(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementResourceViews, id)
	return err
}

const listResources = `-- name: ListResources :many
SELECT id, title, password_hash, filename, file_size, content_type, views, uploaded_by, category_id, transcode_status, created_at, updated_at FROM resources ORDER BY created_at DESC
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PasswordHash,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.Views,
			&i.UploadedBy,
			&i.CategoryID,
			&i.TranscodeStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByTranscodeStatus = `-- name: ListResourcesByTranscodeStatus :many
SELECT id, title, password_hash, filename, file_size, content_type, views, uploaded_by, category_id, transcode_status, created_at, updated_at FROM resources WHERE transcode_status = ? ORDER BY created_at DESC
`

func (q *Queries) ListResourcesByTranscodeStatus(ctx context.Context, transcodeStatus string) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByTranscodeStatus, transcodeStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PasswordHash,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.Views,
			&i.UploadedBy,
			&i.CategoryID,
			&i.TranscodeStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUploader = `-- name: ListResourcesByUploader :many
SELECT id, title, password_hash, filename, file_size, content_type, views, uploaded_by, category_id, transcode_status, created_at, updated_at FROM resources WHERE uploaded_by = ? ORDER BY created_at DESC
`

func (q *Queries) ListResourcesByUploader(ctx context.Context, uploadedBy sql.NullString) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUploader, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PasswordHash,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.Views,
			&i.UploadedBy,
			&i.CategoryID,
			&i.TranscodeStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUploaderPaginated = `-- name: ListResourcesByUploaderPaginated :many
SELECT id, title, password_hash, filename, file_size, content_type, views, uploaded_by, category_id, transcode_status, created_at, updated_at FROM resources WHERE uploaded_by = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListResourcesByUploaderPaginatedParams struct {
	UploadedBy sql.NullString
	Limit      int64
	Offset     int64
}

func (q *Queries) ListResourcesByUploaderPaginated(ctx context.Context, arg ListResourcesByUploaderPaginatedParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUploaderPaginated, arg.UploadedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PasswordHash,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.Views,
			&i.UploadedBy,
			&i.CategoryID,
			&i.TranscodeStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesPaginated = `-- name: ListResourcesPaginated :many
SELECT id, title, password_hash, filename, file_size, content_type, views, uploaded_by, category_id, transcode_status, created_at, updated_at FROM resources ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListResourcesPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListResourcesPaginated(ctx context.Context, arg ListResourcesPaginatedParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PasswordHash,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.Views,
			&i.UploadedBy,
			&i.CategoryID,
			&i.TranscodeStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTranscodeStatus = `-- name: UpdateTranscodeStatus :exec
UPDATE resources SET transcode_status = ? WHERE id = ?
`

type UpdateTranscodeStatusParams struct {
	TranscodeStatus string
	ID              string
}

func (q *Queries) UpdateTranscodeStatus(ctx context.Context, arg UpdateTranscodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTranscodeStatus, arg.TranscodeStatus, arg.ID)
	return err
}
