// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package database

import (
	"context"
)

const addResourceCategory = `-- name: AddResourceCategory :exec
INSERT INTO resource_categories (resource_id, category_name) VALUES (?, ?)
`

type AddResourceCategoryParams struct {
	ResourceID   string
	CategoryName string
}

func (q *Queries) AddResourceCategory(ctx context.Context, arg AddResourceCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addResourceCategory, arg.ResourceID, arg.CategoryName)
	return err
}

const countResources = `-- name: CountResources :one
SELECT COUNT(*) FROM resources
`

func (q *Queries) CountResources(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourcesByCategory = `-- name: CountResourcesByCategory :one
SELECT COUNT(*) FROM resource_categories WHERE category_name = ?
`

func (q *Queries) CountResourcesByCategory(ctx context.Context, categoryName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResourcesByCategory, categoryName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourcesByType = `-- name: CountResourcesByType :one
SELECT COUNT(*) FROM resources WHERE resource_type = ?
`

func (q *Queries) CountResourcesByType(ctx context.Context, resourceType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResourcesByType, resourceType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourcesByUploader = `-- name: CountResourcesByUploader :one
SELECT COUNT(*) FROM resources WHERE uploaded_by = ?
`

func (q *Queries) CountResourcesByUploader(ctx context.Context, uploadedBy string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResourcesByUploader, uploadedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :exec
INSERT INTO resources (id, title, filename, file_size, content_type, resource_type, uploaded_by, no_transcode) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateResourceParams struct {
	ID           string
	Title        string
	Filename     string
	FileSize     int64
	ContentType  string
	ResourceType string
	UploadedBy   string
	NoTranscode  int64
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) error {
	_, err := q.db.ExecContext(ctx, createResource,
		arg.ID,
		arg.Title,
		arg.Filename,
		arg.FileSize,
		arg.ContentType,
		arg.ResourceType,
		arg.UploadedBy,
		arg.NoTranscode,
	)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, title, filename, file_size, content_type, resource_type, views, uploaded_by, transcode_status, banned, no_transcode, created_at, updated_at FROM resources WHERE id = ?
`

func (q *Queries) GetResource(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.FileSize,
		&i.ContentType,
		&i.ResourceType,
		&i.Views,
		&i.UploadedBy,
		&i.TranscodeStatus,
		&i.Banned,
		&i.NoTranscode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceCategoryCount = `-- name: GetResourceCategoryCount :one
SELECT COUNT(*) FROM resource_categories WHERE resource_id = ?
`

func (q *Queries) GetResourceCategoryCount(ctx context.Context, resourceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getResourceCategoryCount, resourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementResourceViews = `-- name: IncrementResourceViews :exec
UPDATE resources SET views = views + 1 WHERE id = ?
`

func (q *Queries) IncrementResourceViews(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementResourceViews, id)
	return err
}

const listResourceCategories = `-- name: ListResourceCategories :many
SELECT category_name FROM resource_categories WHERE resource_id = ?
`

func (q *Queries) ListResourceCategories(ctx context.Context, resourceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listResourceCategories, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category_name string
		if err := rows.Scan(&category_name); err != nil {
			return nil, err
		}
		items = append(items, category_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, title, filename, file_size, content_type, resource_type, views, uploaded_by, transcode_status, banned, no_transcode, created_at, updated_at FROM resources ORDER BY created_at DESC
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.ResourceType,
			&i.Views,
			&i.UploadedBy,
			&i.TranscodeStatus,
			&i.Banned,
			&i.NoTranscode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCategoryPaginated = `-- name: ListResourcesByCategoryPaginated :many
SELECT r.id, r.title, r.filename, r.file_size, r.content_type, r.resource_type, r.views, r.uploaded_by, r.transcode_status, r.banned, r.no_transcode, r.created_at, r.updated_at FROM resources r JOIN resource_categories rc ON r.id = rc.resource_id WHERE rc.category_name = ? ORDER BY r.created_at DESC LIMIT ? OFFSET ?
`

type ListResourcesByCategoryPaginatedParams struct {
	CategoryName string
	Limit        int64
	Offset       int64
}

func (q *Queries) ListResourcesByCategoryPaginated(ctx context.Context, arg ListResourcesByCategoryPaginatedParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByCategoryPaginated, arg.CategoryName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.ResourceType,
			&i.Views,
			&i.UploadedBy,
			&i.TranscodeStatus,
			&i.Banned,
			&i.NoTranscode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByTranscodeStatus = `-- name: ListResourcesByTranscodeStatus :many
SELECT id, title, filename, file_size, content_type, resource_type, views, uploaded_by, transcode_status, banned, no_transcode, created_at, updated_at FROM resources WHERE transcode_status = ? ORDER BY created_at DESC
`

func (q *Queries) ListResourcesByTranscodeStatus(ctx context.Context, transcodeStatus string) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByTranscodeStatus, transcodeStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.ResourceType,
			&i.Views,
			&i.UploadedBy,
			&i.TranscodeStatus,
			&i.Banned,
			&i.NoTranscode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByTypePaginated = `-- name: ListResourcesByTypePaginated :many
SELECT id, title, filename, file_size, content_type, resource_type, views, uploaded_by, transcode_status, banned, no_transcode, created_at, updated_at FROM resources WHERE resource_type = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListResourcesByTypePaginatedParams struct {
	ResourceType string
	Limit        int64
	Offset       int64
}

func (q *Queries) ListResourcesByTypePaginated(ctx context.Context, arg ListResourcesByTypePaginatedParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByTypePaginated, arg.ResourceType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.ResourceType,
			&i.Views,
			&i.UploadedBy,
			&i.TranscodeStatus,
			&i.Banned,
			&i.NoTranscode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUploader = `-- name: ListResourcesByUploader :many
SELECT id, title, filename, file_size, content_type, resource_type, views, uploaded_by, transcode_status, banned, no_transcode, created_at, updated_at FROM resources WHERE uploaded_by = ? ORDER BY created_at DESC
`

func (q *Queries) ListResourcesByUploader(ctx context.Context, uploadedBy string) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUploader, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.ResourceType,
			&i.Views,
			&i.UploadedBy,
			&i.TranscodeStatus,
			&i.Banned,
			&i.NoTranscode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUploaderPaginated = `-- name: ListResourcesByUploaderPaginated :many
SELECT id, title, filename, file_size, content_type, resource_type, views, uploaded_by, transcode_status, banned, no_transcode, created_at, updated_at FROM resources WHERE uploaded_by = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListResourcesByUploaderPaginatedParams struct {
	UploadedBy string
	Limit      int64
	Offset     int64
}

func (q *Queries) ListResourcesByUploaderPaginated(ctx context.Context, arg ListResourcesByUploaderPaginatedParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUploaderPaginated, arg.UploadedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.ResourceType,
			&i.Views,
			&i.UploadedBy,
			&i.TranscodeStatus,
			&i.Banned,
			&i.NoTranscode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesPaginated = `-- name: ListResourcesPaginated :many
SELECT id, title, filename, file_size, content_type, resource_type, views, uploaded_by, transcode_status, banned, no_transcode, created_at, updated_at FROM resources ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListResourcesPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListResourcesPaginated(ctx context.Context, arg ListResourcesPaginatedParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.FileSize,
			&i.ContentType,
			&i.ResourceType,
			&i.Views,
			&i.UploadedBy,
			&i.TranscodeStatus,
			&i.Banned,
			&i.NoTranscode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllResourceCategories = `-- name: RemoveAllResourceCategories :exec
DELETE FROM resource_categories WHERE resource_id = ?
`

func (q *Queries) RemoveAllResourceCategories(ctx context.Context, resourceID string) error {
	_, err := q.db.ExecContext(ctx, removeAllResourceCategories, resourceID)
	return err
}

const removeResourceFromCategory = `-- name: RemoveResourceFromCategory :exec
DELETE FROM resource_categories WHERE resource_id = ? AND category_name = ?
`

type RemoveResourceFromCategoryParams struct {
	ResourceID   string
	CategoryName string
}

func (q *Queries) RemoveResourceFromCategory(ctx context.Context, arg RemoveResourceFromCategoryParams) error {
	_, err := q.db.ExecContext(ctx, removeResourceFromCategory, arg.ResourceID, arg.CategoryName)
	return err
}

const updateResourceBanned = `-- name: UpdateResourceBanned :exec
UPDATE resources SET banned = ? WHERE id = ?
`

type UpdateResourceBannedParams struct {
	Banned int64
	ID     string
}

func (q *Queries) UpdateResourceBanned(ctx context.Context, arg UpdateResourceBannedParams) error {
	_, err := q.db.ExecContext(ctx, updateResourceBanned, arg.Banned, arg.ID)
	return err
}

const updateTranscodeStatus = `-- name: UpdateTranscodeStatus :exec
UPDATE resources SET transcode_status = ? WHERE id = ?
`

type UpdateTranscodeStatusParams struct {
	TranscodeStatus string
	ID              string
}

func (q *Queries) UpdateTranscodeStatus(ctx context.Context, arg UpdateTranscodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTranscodeStatus, arg.TranscodeStatus, arg.ID)
	return err
}
