// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_resource.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createShareResource = `-- name: CreateShareResource :exec
INSERT INTO share_resources (resource_id, password, expires_at, created_by, created_at) VALUES (?, ?, ?, ?, ?)
`

type CreateShareResourceParams struct {
	ResourceID string
	Password   string
	ExpiresAt  sql.NullTime
	CreatedBy  string
	CreatedAt  time.Time
}

func (q *Queries) CreateShareResource(ctx context.Context, arg CreateShareResourceParams) error {
	_, err := q.db.ExecContext(ctx, createShareResource,
		arg.ResourceID,
		arg.Password,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredShareResources = `-- name: DeleteExpiredShareResources :exec
DELETE FROM share_resources WHERE expires_at IS NOT NULL AND expires_at <= ?
`

func (q *Queries) DeleteExpiredShareResources(ctx context.Context, expiresAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredShareResources, expiresAt)
	return err
}

const deleteShareResource = `-- name: DeleteShareResource :exec
DELETE FROM share_resources WHERE resource_id = ? AND password = ?
`

type DeleteShareResourceParams struct {
	ResourceID string
	Password   string
}

func (q *Queries) DeleteShareResource(ctx context.Context, arg DeleteShareResourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteShareResource, arg.ResourceID, arg.Password)
	return err
}

const getShareResource = `-- name: GetShareResource :one
SELECT resource_id, password, expires_at, created_by, created_at FROM share_resources WHERE resource_id = ? AND password = ? AND (expires_at IS NULL OR expires_at > ?)
`

type GetShareResourceParams struct {
	ResourceID string
	Password   string
	ExpiresAt  sql.NullTime
}

func (q *Queries) GetShareResource(ctx context.Context, arg GetShareResourceParams) (ShareResource, error) {
	row := q.db.QueryRowContext(ctx, getShareResource, arg.ResourceID, arg.Password, arg.ExpiresAt)
	var i ShareResource
	err := row.Scan(
		&i.ResourceID,
		&i.Password,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listShareResources = `-- name: ListShareResources :many
SELECT resource_id, password, expires_at, created_by, created_at FROM share_resources WHERE resource_id = ? AND (expires_at IS NULL OR expires_at > ?) ORDER BY created_at DESC
`

type ListShareResourcesParams struct {
	ResourceID string
	ExpiresAt  sql.NullTime
}

func (q *Queries) ListShareResources(ctx context.Context, arg ListShareResourcesParams) ([]ShareResource, error) {
	rows, err := q.db.QueryContext(ctx, listShareResources, arg.ResourceID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareResource{}
	for rows.Next() {
		var i ShareResource
		if err := rows.Scan(
			&i.ResourceID,
			&i.Password,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
