// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_link.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createShareLink = `-- name: CreateShareLink :exec
INSERT INTO share_links (id, password, target_type, target_id, expires_at, created_by, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateShareLinkParams struct {
	ID         string
	Password   string
	TargetType string
	TargetID   string
	ExpiresAt  sql.NullTime
	CreatedBy  string
	CreatedAt  time.Time
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) error {
	_, err := q.db.ExecContext(ctx, createShareLink,
		arg.ID,
		arg.Password,
		arg.TargetType,
		arg.TargetID,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredShareLinks = `-- name: DeleteExpiredShareLinks :exec
DELETE FROM share_links WHERE expires_at IS NOT NULL AND expires_at <= ?
`

func (q *Queries) DeleteExpiredShareLinks(ctx context.Context, expiresAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredShareLinks, expiresAt)
	return err
}

const deleteShareLink = `-- name: DeleteShareLink :exec
DELETE FROM share_links WHERE id = ?
`

func (q *Queries) DeleteShareLink(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteShareLink, id)
	return err
}

const getShareLink = `-- name: GetShareLink :one
SELECT id, password, target_type, target_id, expires_at, created_by, created_at FROM share_links WHERE id = ? AND (expires_at IS NULL OR expires_at > ?)
`

type GetShareLinkParams struct {
	ID        string
	ExpiresAt sql.NullTime
}

func (q *Queries) GetShareLink(ctx context.Context, arg GetShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRowContext(ctx, getShareLink, arg.ID, arg.ExpiresAt)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.TargetType,
		&i.TargetID,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listShareLinksByTarget = `-- name: ListShareLinksByTarget :many
SELECT id, password, target_type, target_id, expires_at, created_by, created_at FROM share_links WHERE target_type = ? AND target_id = ? AND (expires_at IS NULL OR expires_at > ?) ORDER BY created_at DESC
`

type ListShareLinksByTargetParams struct {
	TargetType string
	TargetID   string
	ExpiresAt  sql.NullTime
}

func (q *Queries) ListShareLinksByTarget(ctx context.Context, arg ListShareLinksByTargetParams) ([]ShareLink, error) {
	rows, err := q.db.QueryContext(ctx, listShareLinksByTarget, arg.TargetType, arg.TargetID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLink{}
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.Password,
			&i.TargetType,
			&i.TargetID,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
