// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package database

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM users WHERE is_admin = 1
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, totp_secret, display_name, is_admin) VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	Name        string
	TotpSecret  string
	DisplayName string
	IsAdmin     int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.TotpSecret,
		arg.DisplayName,
		arg.IsAdmin,
	)
	return err
}

const getAdminName = `-- name: GetAdminName :one
SELECT name FROM users WHERE is_admin = 1 LIMIT 1
`

func (q *Queries) GetAdminName(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAdminName)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT name, totp_secret, display_name, is_admin, created_at FROM users WHERE is_admin = 1 LIMIT 1
`

func (q *Queries) GetAdminUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getAdminUser)
	var i User
	err := row.Scan(
		&i.Name,
		&i.TotpSecret,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT name, totp_secret, display_name, is_admin, created_at FROM users WHERE name = ?
`

func (q *Queries) GetUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i User
	err := row.Scan(
		&i.Name,
		&i.TotpSecret,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT name, totp_secret, display_name, is_admin, created_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Name,
			&i.TotpSecret,
			&i.DisplayName,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
